<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProveedoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('proveedores')->insert([
            [
                'codigo' => 'PRV-001',
                'tipo_proveedor' => 'DISTRIBUIDOR',
                'razon_social' => 'Audifarma S.A.',
                'nombre_comercial' => 'Audifarma',
                'nit' => '816001234',
                'digito_verificacion' => '5',
                'registro_invima' => 'INV-2023-XXXX',
                'habilitacion_salud' => 'HAB-816001234',
                'direccion' => 'Zona Industrial, Bodega 5',
                'ciudad' => 'Cali',
                'departamento' => 'Valle del Cauca',
                'pais' => 'Colombia',
                'telefono' => '6021234567',
                'celular' => '3001234567',
                'email' => 'contacto@audifarma.com.co',
                'sitio_web' => 'https://www.audifarma.com.co',
                'contacto_comercial' => 'Carlos Perez',
                'telefono_contacto' => '3001234567',
                'email_contacto' => 'cperez@audifarma.com.co',
                'contacto_farmacovigilancia' => 'Maria Gomez',
                'contacto_logistica' => 'Juan Rodriguez',
                'condiciones_pago' => 'Crédito a 60 días',
                'dias_credito' => 60,
                'maneja_cadena_frio' => 1,
                'temperatura_min' => 2.00,
                'temperatura_max' => 8.00,
                'tiempo_entrega_horas' => 24,
                'horario_entrega' => 'Lunes a Viernes 8am - 5pm',
                'certificaciones' => 'ISO 9001, BPM, BPA',
                'observaciones' => 'Proveedor principal de medicamentos en el suroccidente.',
                'logo' => null,
                'estado' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'codigo' => 'PRV-002',
                'tipo_proveedor' => 'LABORATORIO',
                'razon_social' => 'Bayer de Colombia S.A.',
                'nombre_comercial' => 'Bayer',
                'nit' => '860001234',
                'digito_verificacion' => '1',
                'registro_invima' => 'INV-BAYER-2023',
                'habilitacion_salud' => 'HAB-860001234',
                'direccion' => 'Calle 100 # 50-20',
                'ciudad' => 'Bogotá',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'telefono' => '6012345678',
                'celular' => '3101234567',
                'email' => 'ventas@bayer.com.co',
                'sitio_web' => 'https://www.bayer.com.co',
                'contacto_comercial' => 'Ana Martinez',
                'telefono_contacto' => '3101234567',
                'email_contacto' => 'amartinez@bayer.com.co',
                'contacto_farmacovigilancia' => 'Luisa Fernandez',
                'contacto_logistica' => 'Pedro Hernandez',
                'condiciones_pago' => 'Crédito a 30 días',
                'dias_credito' => 30,
                'maneja_cadena_frio' => 0,
                'temperatura_min' => null,
                'temperatura_max' => null,
                'tiempo_entrega_horas' => 48,
                'horario_entrega' => 'Lunes a Viernes 7am - 4pm',
                'certificaciones' => 'ISO 9001, ISO 14001, BPM',
                'observaciones' => 'Laboratorio internacional, compras directas.',
                'logo' => null,
                'estado' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'codigo' => 'PRV-003',
                'tipo_proveedor' => 'OPERADOR_LOGISTICO',
                'razon_social' => 'Logística Farmacéutica Especializada SAS',
                'nombre_comercial' => 'LogiFarma',
                'nit' => '900123456',
                'digito_verificacion' => '7',
                'registro_invima' => null,
                'habilitacion_salud' => 'HAB-900123456',
                'direccion' => 'Autopista Sur Km 5',
                'ciudad' => 'Medellín',
                'departamento' => 'Antioquia',
                'pais' => 'Colombia',
                'telefono' => '6043216547',
                'celular' => '3203216547',
                'email' => 'operaciones@logifarma.com',
                'sitio_web' => 'https://www.logifarma.com',
                'contacto_comercial' => 'Roberto Ruiz',
                'telefono_contacto' => '3203216547',
                'email_contacto' => 'rruiz@logifarma.com',
                'contacto_farmacovigilancia' => null,
                'contacto_logistica' => 'Sofia Castro',
                'condiciones_pago' => 'Contado',
                'dias_credito' => 0,
                'maneja_cadena_frio' => 1,
                'temperatura_min' => 2.00,
                'temperatura_max' => 8.00,
                'tiempo_entrega_horas' => 12,
                'horario_entrega' => '24 horas',
                'certificaciones' => 'BPA, BPL',
                'observaciones' => 'Aliado estratégico para recolección nacional.',
                'logo' => null,
                'estado' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'codigo' => 'PRV-004',
                'tipo_proveedor' => 'DROGUERIA',
                'razon_social' => 'Copidrogas Cooperativa Nacional',
                'nombre_comercial' => 'Copidrogas',
                'nit' => '860025123',
                'digito_verificacion' => '9',
                'registro_invima' => 'INV-COP-2024',
                'habilitacion_salud' => 'HAB-860025123',
                'direccion' => 'Vía Siberia Cota Km 1',
                'ciudad' => 'Cota',
                'departamento' => 'Cundinamarca',
                'pais' => 'Colombia',
                'telefono' => '6018765432',
                'celular' => '3118765432',
                'email' => 'ventas@copidrogas.com.co',
                'sitio_web' => 'https://www.copidrogas.com.co',
                'contacto_comercial' => 'Ricardo Gómez',
                'telefono_contacto' => '3118765432',
                'email_contacto' => 'rgomez@copidrogas.com.co',
                'contacto_farmacovigilancia' => 'Andrea Rios',
                'contacto_logistica' => 'Mario Diaz',
                'condiciones_pago' => 'Crédito a 45 días',
                'dias_credito' => 45,
                'maneja_cadena_frio' => 1,
                'temperatura_min' => 2.00,
                'temperatura_max' => 8.00,
                'tiempo_entrega_horas' => 24,
                'horario_entrega' => 'Lunes a Sábado 8am - 6pm',
                'certificaciones' => 'BPA',
                'observaciones' => '',
                'logo' => null,
                'estado' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'codigo' => 'PRV-005',
                'tipo_proveedor' => 'INSUMOS',
                'razon_social' => 'Insumos Médicos del Valle SAS',
                'nombre_comercial' => 'Insumed',
                'nit' => '901234567',
                'digito_verificacion' => '2',
                'registro_invima' => 'INV-INSU-2023',
                'habilitacion_salud' => 'HAB-901234567',
                'direccion' => 'Carrera 15 # 20-30',
                'ciudad' => 'Bucaramanga',
                'departamento' => 'Santander',
                'pais' => 'Colombia',
                'telefono' => '6076543210',
                'celular' => '3156543210',
                'email' => 'contacto@insumed.com',
                'sitio_web' => 'https://www.insumed.com',
                'contacto_comercial' => 'Diana Lopez',
                'telefono_contacto' => '3156543210',
                'email_contacto' => 'dlopez@insumed.com',
                'contacto_farmacovigilancia' => null,
                'contacto_logistica' => 'Luis Suarez',
                'condiciones_pago' => 'Crédito a 30 días',
                'dias_credito' => 30,
                'maneja_cadena_frio' => 0,
                'temperatura_min' => null,
                'temperatura_max' => null,
                'tiempo_entrega_horas' => 72,
                'horario_entrega' => 'Lunes a Viernes 8am - 12pm',
                'certificaciones' => 'ISO 9001',
                'observaciones' => 'Proveedor de jeringas, gasas y material médico-quirúrgico.',
                'logo' => null,
                'estado' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);
    }
}
